#CREATE DATABASE tecmicro;

CREATE TABLE TB_USUARIO (
	ID_USUARIO int PRIMARY KEY NOT NULL,
	NM_USUARIO varchar(255) NOT NULL,
	DS_FOTO blob,
	DT_CRIACAO datetime NOT NULL,
	DT_ATUALIZACAO datetime NOT NULL
);

CREATE TABLE TB_POST (
	ID_POST bigint(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	DS_TITLE varchar(255) NOT NULL,
	DS_CONTENT varchar(1000) NOT NULL,
	DT_CRIACAO datetime NOT NULL,
	DT_ATUALIZACAO datetime NOT NULL,
	NR_VISITAS int NOT NULL,
	NR_VOTOS int NOT NULL,
	ID_USUARIO int NOT NULL
);

ALTER TABLE TB_POST ADD CONSTRAINT FK_POST_USUARIO FOREIGN KEY ( ID_USUARIO ) 
	REFERENCES TB_USUARIO ( ID_USUARIO ) ;

CREATE TABLE TB_RESPOSTA (
	ID_RESPOSTA bigint(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	DS_CONTENT varchar(1000) NOT NULL,
	DT_CRIACAO datetime NOT NULL,
	DT_ATUALIZACAO datetime NOT NULL,
	NR_VOTOS int NOT NULL,
	ID_USUARIO int NOT NULL,
	ID_POST bigint(20) NOT NULL
);

ALTER TABLE TB_RESPOSTA ADD CONSTRAINT FK_RESPOSTA_POST FOREIGN KEY ( ID_POST ) 
	REFERENCES TB_POST ( ID_POST ) ;

ALTER TABLE TB_RESPOSTA ADD CONSTRAINT FK_RESPOSTA_USUARIO FOREIGN KEY ( ID_USUARIO ) 
	REFERENCES TB_USUARIO ( ID_USUARIO ) ;
	